# Generated by Django 4.2.4 on 2023-08-16 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='thumb_filmes')),
                ('descricao', models.TextField(max_length=1000)),
                ('categoria', models.CharField(choices=[('ROCK', 'Rock'), ('OUTROS', 'Outros'), ('MPB', 'MPB'), ('POP', 'Pop')], max_length=10)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2023, 8, 16, 0, 30, 56, 288605, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
