# Generated by Django 4.2.4 on 2023-08-16 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('OUTROS', 'Outros'), ('MPB', 'MPB')], max_length=10),
        ),
        migrations.AlterField(
            model_name='filme',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 0, 33, 44, 79687, tzinfo=datetime.timezone.utc)),
        ),
    ]
